### ISSUE TITLE
Extending the web (with browser extensions)

### ISSUE THREAD

**Issue by dgil** [BarcelonaJS/old.barcelonajs.org#71]
---
level: advanced
language: en | es
twitter: vulljugar
tags:
  - chrome-extension
  - firefox-extension
  - yeoman

---

You use Firefox extensions (or Chrome extensions) all the time, but do you really know the potential of them? 

In this talk I want to show  how easy is to develop a Firefox extension and through some examples, showing the power that allows the API of Firefox and Chrome.

**Comment by repejota** [comment]
Can we close this or move it to the planning repo?

**Comment by PatrickHeneise** [comment]
BarcelonaJS/speakers ... not planning ;)
