### ISSUE TITLE
Organisers Meetup

### ISSUE THREAD

**Issue by PatrickHeneise** [BarcelonaJS/old.barcelonajs.org#73]
Wednesday, 29.07.2015

Open to everyone who's interested to collaborate with BarcelonaJS.

19.00 - ALSUR CAFÉ - EL BORN

Topics:
- MediterráneaJS review
- BarcelonaJS organisation and partner events (AngularBCN, AngularBeers, ReactBCN, ...)
- BarcelonaJS upcoming schedule
- The future of BarcelonaJS
- :beers:

**Comment by leonkyr** [comment]
The place is 
https://www.google.com/maps/place/Alsur+Caf%C3%A9+El+Born/@41.3866499,2.180687,17z/data=!4m2!3m1!1s0x12a4a2fc117f53fd:0xbadfa5f3fba43a30

**Comment by PatrickHeneise** [comment]
Exactly. There we should have enough quiet space to talk.

Also for the list:

- BarcelonaJS August: BeachJS? JS BBQ?

**Comment by PatrickHeneise** [comment]
# BarcelonaJS Founders Meeting
Meeting Notes, 29.07.

## MediterráneaJS Review
DO: Follow up with feedback/questionnaire
DO: Cut videos

### The good:
- Feedback about Q&A sessions
- Diversity

### The bad:
- 3500,- EUR on services that were not communicated / not calculated with
- Sound and video issues on the first day
- WiFi issues
- No Networking area
- No clear focus of the conference (community or not)

## BarcelonaJS - The Future
- ~50€ yearly fee to pay for accountant and other things (Meetup.com, various domains, etc.)
- Membership gives discount on special events and conferences
- two types: member and associate
- DO: List of perks for members

## BarcelonaJS and other JS groups
- "Flavours of BarcelonaJS" - monthly events with focus on a framework
- GitHub issues (=talks) control supply and demand of framework specific talks
- No other groups, it's all in BarcelonaJS

## BarcelonaJS BBQ.js
28.08. at Typeform. Bring your own food, beer will be provided.

**Comment by repejota** [comment]
Can we close this?
